modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/CrychicTeam/Champions/issues"
logoFile="champions_icon.png"
logoBlur=false
[[mods]]
modId="${mod_id}"
version="${mod_version}" #mandatory
# A display name for the mod
displayName="${mod_name}" #mandatory
displayURL="https://github.com/CrychicTeam/Champions"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
  modId="forge"
  mandatory=true
  versionRange="${forge_version_range}"
  ordering="NONE"
  side="BOTH"
[[dependencies.${mod_id}]]
  modId="minecraft"
  mandatory=true
  versionRange="${minecraft_version_range}"
  ordering="NONE"
  side="BOTH"
[[dependencies.${mod_id}]]
  modId="scalinghealth"
  mandatory=false
  versionRange="${scalinghealth_version_range}"
