@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package top.theillusivec4.champions.common.integration.gateways_to_eternity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
