@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package top.theillusivec4.champions.common.integration.gateways_to_eternity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
